### PR TITLE
✨️ NEW: Adding CI Tools

### PR DESCRIPTION
**Pull request by AakashGfude**

### CODE REVIEW

**Comment by AakashGfude** [comment]
@mmcky, just figuring out a way to rename `Netlify` to `Project preview`.

**Comment by mmcky** [comment]
should just be the top of the `yml` file in `.github/workflows`

**Comment by AakashGfude** [comment]
@mmcky that is `Example project build` in this case and the corresponding step name for this one is also `Preview Deploy to Netlify`, in `.github/workflows/tests.yml`. I reckon the one being discussed is directly inputted here by the Netlify server? Do you think there is a place in the Netlify dashboard to rename this?

**Comment by mmcky** [comment]
> @mmcky that is `Example project build` in this case and the corresponding step name for this one is also `Preview Deploy to Netlify`, in `.github/workflows/tests.yml`. I reckon the one being discussed is directly inputted here by the Netlify server? Do you think there is a place in the Netlify dashboard to rename this?

If that is the case -- no worries @AakashGfude. 

@AakashGfude I think I just touched some files that are now in conflict. Sorry. Want me to take a look?

**Comment by AakashGfude** [comment]
> @AakashGfude I think I just touched some files that are now in conflict. Sorry. Want me to take a look?

that would be nice. thanks @mmcky

**Comment by mmcky** [comment]
@AakashGfude fixed up the conflicts -- can you review pre-commit again. Thanks.

**Review by mmcky — CHANGES_REQUESTED** [review]
@AakashGfude thanks -- this is looking great.

One last request. Can you please add some documentation for what is needed for contributing. Is this already in the `docs`? (i.e. install pre-commit) etc.

**Comment by AakashGfude** [comment]
@mmcky will review the documentation on contribution now.

**Comment by AakashGfude** [comment]
@mmcky have added a contributing doc now. Do suggest/do edits

**Review by mmcky — APPROVED** [review]

**Comment by mmcky** [comment]
@AakashGfude just getting this on `pytest` -- do you think we need to address this?

```
tests/test_build.py::test_basic
/sphinxcontrib-tomyst/sphinxcontrib/tomyst/writers/markdown.py:79: DeprecationWarning: invalid escape sequence \[
    return "\["  # noqa: W605
sphinxcontrib-tomyst/sphinxcontrib/tomyst/writers/markdown.py:82: DeprecationWarning: invalid escape sequence \]
    return "\]"  # noqa: W605

-- Docs: https://docs.pytest.org/en/latest/warnings.html
```

**Comment by mmcky** [comment]
@AakashGfude I have removed the `\`

**Pull request merged**
